### ISSUE TITLE
Distribution build

### ISSUE THREAD

**Issue by mheiber** [tom-s/react-drag-sortable#1]
Great job! I love the examples and configurability.

Do you have plans to add a build step? We exclude `node_modules` when running Babel, so I get a syntax error when trying to import and use the module.

**Comment by tom-s** [comment]
Hi,

Thanks for trying this module. I'm quite busy at the moment but I'll add a build step for ES5 as soon as possible (in the next 20 days)

**Comment by tom-s** [comment]
Hi there,

I moved my code to ES6 and added a build stage. There was also an error with the package.json not pointing to the main file, which would explain your import issues.

It's been all fixed, let me know if it works for you !

**Comment by mheiber** [comment]
@tom-s thanks, this works great!
