### ISSUE TITLE
Small Issue When changing the type = "grid"

### ISSUE THREAD

**Issue by naikhpratik** [tom-s/react-drag-sortable#10]
In draggable class when I am trying to override float to none instead of left (which is set by default in library) it does not work. And then when I try to do it with !important it gives me some rank error

1. ![image](https://cloud.githubusercontent.com/assets/13668787/25015876/b5781c7a-204b-11e7-99a1-32b95162f791.png)

2.  ![image](https://cloud.githubusercontent.com/assets/13668787/25015961/1d25a0cc-204c-11e7-8400-5bf6fb3e1fb0.png)

It is a small issue but never worked on something like this. Could you please tell me how to make it work with **Float : none**

**Comment by tom-s** [comment]
Can you tell me more ? What are you trying to achieve by removing the float ? Do you replace it wwith a display inline-block ? Elements needs to be next to each other to constitute a grid.

**Comment by naikhpratik** [comment]
![image](https://cloud.githubusercontent.com/assets/13668787/25154346/4f6dadd4-245e-11e7-9373-288f2f27f650.png)

I am using the Library to move these images. It works fine when type is not grid (i.e it displays the same way as shown in the pic above) but when I change it to type="grid". The div in which the images are displayed move everything to its left.  And when I try to override it in site.css file it shows me the following error when I move the file.

I am trying to do like this 
![image](https://cloud.githubusercontent.com/assets/13668787/25154612/57764ad0-245f-11e7-9a6c-0aabc95579af.png)

**Comment by tom-s** [comment]
It looks more like a css issue (the float: left is required for the grid to work).
If you give me an example of code I'll be happy to look at it.

**Comment by naikhpratik** [comment]
```javascript
var Image = React.createClass({
    render: function () {
        var primaryClass = this.props.img.Primary ? "fa fa-star" : "fa fa-star-o";
        var moveItemUp, moveItemDown = '';
        return (
            <div className="col-xs-4">
                 <img className="img-responsive" src={this.props.img.Images.Thumb} />
                 <div className="pull-left btn btn-link">
                     <i onClick={(e) => this.props.callbacks.setPrimary(this.props.img)} className={primaryClass} />
                 </div>
                <div className="pull-right btn btn-link">
                    <i onClick={(e) => this.props.callbacks.delete(this.props.img)} className="text-danger fa fa-times" />
                </div>
            </div>
        )
    }
});

var items = this.state.items.map(function (item) {
                return <Image img={item} total={totalCount} key={item.ItemPhotoId} callbacks={callbacks} />
        })
        var drag = [];
        for (let value in items) {
            drag.push(({ content: items[value] }));}
        return (
            <div className="row">
                <DragSortableList items={drag} onSort={this.onSort} dropBackTransitionDuration={0.3} type="vertical" placeholder={placeholder} />
            </div>
        )
```

This is the code that I am using. I have the images wrapped inside the div elements as above. Hence I am getting the error.  Any thoughts ?

**Comment by tom-s** [comment]
I'm affraid that won't help. I need a jsfiddle with the css as well or something like that.

**Comment by tom-s** [comment]
You should keep the float left and fix the problem in your own css (i suspect it's just a css issue)
