### ISSUE TITLE
Disabling drag on form <input> tags?

### ISSUE THREAD

**Issue by saadq** [tom-s/react-drag-sortable#11]
Firstly, much thanks for the easy to use component. I was wondering if there was a way to disable dragging with `<input>` tags. For example, in a situation like this:

![screen shot 2017-04-14 at 4 50 02 pm](https://cloud.githubusercontent.com/assets/5678694/25055722/8c63162c-2132-11e7-8632-c3eaf7d232ae.png)

If you try to use the cursor to select the `1` inside the first input field, it will start dragging the entire box instead of selecting and highlighting the text inside the field. I just wanted to see if you knew of any workarounds or had any advice on how to deal with this situation. Feel free to close otherwise.

I could provide some code if you'd like, but I think it's basically any situation where there is an `<input>` tag inside one if the `items` elements for the `DragSortableList`.

**Comment by FabriceReynolds** [comment]
I'm having the same issue and moreover if I enter text and trigger the onChange the page jumps to the end of the list and I have to scroll back to where I was, to be able to enter the next character. Not sure if this is related to React re-rendering on change. I've tried to preventDefault and stopPropagation on various events and even nativeEvent.stopImmediatePropagation() but to no avail.

**Comment by Swarna-Jain** [comment]
having same issue ... when try to input text after input change cursor switch to end of list.. I have edit buttons in list when click on edit input box displays but when try to edit it, on every character change cursor jump to end of list.. want to stop drag facility until I click save button.

**Comment by tom-s** [comment]
Hi, can somebody provide me with some code example ? I just tried with a list if inputs and couldn't reproduce the issue.

**Comment by Swarna-Jain** [comment]
changetextfieldEdit(e) {
    this.setState({editTitle:e.target.value})
  } 

   handleEdit(e, lbl, ttl) {
    if(lbl === "Edit") {
       this.setState({editMode: e,
                      editTitle: ttl,
                      label: "Save"
                    })
    } else {
      var edit={
      id: e,
      title: this.state.editTitle
    }
    this.setState({editMode: '',
    editTitle: '',
    label: "Edit"})
    }
  }
   categorydataList =  categories.map((val,index)=>{
           return (  
            {content: (<div>
            {
              this.state.editMode === val._id 
              ?
              <div id="listdiveven" key = {index}>
              <TextField
              floatingLabelText="Edit Catagory"
              fullWidth={false}
              value={this.state.editTitle}  onChange={this.changetextfieldEdit.bind(this)}
              />             
              <span className="pull-right list-arrow featured"><RaisedButton label={this.state.label} disabled={this.state.disabled} onTouchTap={this.handleEdit.bind(this, val._id, this.state.label, val.title)} /><img src="../img/top-bottom-arrow.png" className="cancel-btn"/><img src="../img/cancel.png"/></span>
              </div>
              :
               <div id="listdiveven" key = {index}><a href="javascript:void(0)">
              {val.title}
              <span className="pull-right list-arrow featured"><RaisedButton label={this.state.label} disabled={this.state.disabled} onTouchTap={this.handleEdit.bind(this, val._id, this.state.label, val.title)} /><img src="../img/top-bottom-arrow.png" className="cancel-btn"/><img src="../img/cancel.png"/></span></a>
              </div>
            }
            </div>)
         })
      }) 


  var onSortEnd = (sortedList) => {
    let {items} = this.state;  
    let sort=[]
    sortedList.map((item)=>{
        sort.push(item.content.props.children.props.children.props.children[0]); /// need to be changed if content components are changed or else get undefined.
      })  
    this.setState({
      items: sort
    });
 
  };



<DragSortableList className="venue-list" items={categorydataList} onSort={onSortEnd} dropBackTransitionDuration={0.3} type="vertical"/>

**Comment by Swarna-Jain** [comment]
It happens when I try to do inline editing in record as follows:
{content: (<div>
            {
              this.state.editMode === val._id 
              ?
              <div id="listdiveven" key = {index}>
              <TextField
              floatingLabelText="Edit Catagory"
              fullWidth={false}
              disabled = {this.state.disabled}
              value={this.state.editTitle}  onChange={this.changetextfieldEdit.bind(this)}
              />             
              <span className="pull-right list-arrow featured"><RaisedButton label={this.state.label} disabled={this.state.disabled} onTouchTap={this.handleEdit.bind(this, val._id, this.state.label, val.title)} /><img src="../img/top-bottom-arrow.png" className="cancel-btn"/><img src="../img/cancel.png"/></span>
              </div>
              :
               <div id="listdiveven" key = {index}><a href="javascript:void(0)">
              {val.title}
              <span className="pull-right list-arrow featured"><RaisedButton label={this.state.label} disabled={this.state.disabled} onTouchTap={this.handleEdit.bind(this, val._id, this.state.label, val.title)} /><img src="../img/top-bottom-arrow.png" className="cancel-btn"/><img src="../img/cancel.png"/></span></a>
              </div>
            }
            </div>)
         }
In above code component
<TextField
              floatingLabelText="Edit Catagory"
              fullWidth={false}
              disabled = {this.state.disabled}
              value={this.state.editTitle}  onChange={this.changetextfieldEdit.bind(this)}
   />  
requires to stop  dragging when changing its value.

**Comment by Swarna-Jain** [comment]
{content: (<div>
            {
              this.state.editMode === val._id 
              ?
              <div id="listdiveven" key = {index}>
              <TextField
              floatingLabelText="Edit Catagory"
              fullWidth={false}
              disabled = {this.state.disabled}
              value={this.state.editTitle}  onChange={this.changetextfieldEdit.bind(this)}
              />             
              <span className="pull-right list-arrow featured"><RaisedButton label={this.state.label} disabled={this.state.disabled} onTouchTap={this.handleEdit.bind(this, val._id, this.state.label, val.title)} /><img src="../img/top-bottom-arrow.png" className="cancel-btn"/><img src="../img/cancel.png"/></span>
              </div>
              :
               <div id="listdiveven" key = {index}><a href="javascript:void(0)">
              {val.title}
              <span className="pull-right list-arrow featured"><RaisedButton label={this.state.label} disabled={this.state.disabled} onTouchTap={this.handleEdit.bind(this, val._id, this.state.label, val.title)} /><img src="../img/top-bottom-arrow.png" className="cancel-btn"/><img src="../img/cancel.png"/></span></a>
              </div>
            }
            </div>)
         }


In above code TextField doesn't work properly

**Comment by Swarna-Jain** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26534992/26356135/b216ab70-3fe8-11e7-8c77-67f54cabeef6.png)

Here TextField doesn't work properly due to drag facility.

**Comment by tom-s** [comment]
I'm sorry this (screenshot) won't help. You need to reproduce the issue in a jsfiddle (or such) with simple inputs, or at least components we can look at (what is TextField ?).

Please provide a link to a reduced test case that demonstrate the issue.

**Comment by janhoeck** [comment]
@tom-s Just have a Textbox inside a div. Put some of this in a `DragSortableList`
For example: Write something in the textbox and then mark the text in this input. After this the dragging will start. But I wont do that...

There should be the possibility to stop the event.

**Comment by saadq** [comment]
Sorry, I suppose a code sample would have made it easier to see the issue. I'll post one by today.

**Comment by saadq** [comment]
I think the users above me had different issues than I did, but they might be related.

Here is an example repo: https://github.com/saadq/tmp

Steps to reproduce:

1. Clone the repo
2. Run `npm install` or `yarn install`
3. Run `npm start` and go to `http://localhost:3000`
4. Type some words in one of the input fields
5. Try to use mouse drag to select one of the words inside the input. This will cause the entire box to drag instead of allowing you to highlight a word.

**Comment by tom-s** [comment]
Thanks for the code, I understand the issue. It is sort of the expected behavior (the parent being draggable, dragging any of it's children will drag the whole thing). So you'd like to be able to have children within a draggable element which don't trigger dragging. It's not currently possible, but I will keep it mind for v2 (work in progress at the moment, it's a complete rewrite of the api) of this library. In the meantime do not hesitate to submit PR if  you know how to achieve that.

**Comment by saadq** [comment]
Thanks for the response! And yeah, I'll try to see if I can play around with your code to make this work.

**Comment by janhoeck** [comment]
@saadq Did you reached a little goal yet?

**Comment by saadq** [comment]
Sorry, but I haven't gotten a chance to try messing around with it as I have some of my own issues to fix right now. I'm not sure when I'll have time to play around with it :/

**Comment by janhoeck** [comment]
Hello everybody,

i fixed the problem. Just put this code at the start of the _dragMove(event) method:

> // get the element where the mouse is
        const mouseElement = document.elementFromPoint(event.clientX, event.clientY);
        // check if the element has a class name that should stop the dragging
        if (mouseElement.classList.contains('stop-drag')) {
            // stop the dragging!
            interact.stop(event);
            return;
        }

Now give your input field a 'stop-drag' class. Done.

**Comment by tom-s** [comment]
That could easily be implemented in the library :+1:

**Comment by janhoeck** [comment]
Could you do it or should I do an Pullrequest?

**Comment by tom-s** [comment]
I've implemented it but your solution does not seem to work.
See https://github.com/tom-s/react-drag-sortable/pull/14
Please feel free to update the PR with a solution if you have one

**Comment by janhoeck** [comment]
I think line 44 is wrong
`mouseElement && !mouseElement.classList.contains('no-drag')`
Maybe you should change the bool operator?
to: 
`mouseElement && mouseElement.classList.contains('no-drag')`

And what does fun(event) and ignoreNoDrag(...) do? I can't find any documentation.

Did you tried out my code? It works perfectly.

**Comment by tom-s** [comment]
The bool operator is fine. I call fun when the element doesn't have a "no-drag" method.
Fun is the parameter passed to ignore no drag -> this._dragMove.bind(this)

What was missing was actually the interact.stop(event), I've added it and it works now. See if the PR satisfies you.

**Comment by tom-s** [comment]
Version 1.0.4 has been published with the changes, please let me know if it works for you.

**Comment by janhoeck** [comment]
It works! Thanks for your time.
