### ISSUE TITLE
Can the dragEnd event called and return the dragged element?

### ISSUE THREAD

**Issue by Nalrarang** [tom-s/react-drag-sortable#16]
Hi. Good Library.
I need information about the element after dragging a specific element.
Can you return the draggedEl to the onsort function after the dragEnd event?

**Comment by tom-s** [comment]
Hi. I've published version 1.0.5 which returns the dragEnv event (not the browser event but interact.js event) as a second param. It's also been added to the documentation, let me know if it works !

**Comment by Nalrarang** [comment]
It works very well.
Thank you!
