### ISSUE TITLE
React and React-Dom should be peer-dependencies: Error preventing render

### ISSUE THREAD

**Issue by StJohn3D** [tom-s/react-drag-sortable#2]
I love the interface concept and the demo looks great. But I can't use this component because of this error.

>**Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded...**

Changing **`react`** and **`react-dom`** to be peer-dependencies should resolve this.

_Also in the documentation it says
`import DragSortableList from 'react-sortable-list'`
shouldn't that be `'react-drag-sortable'`?_

Here's my test.

```js
import React, { Component } from 'react'
import DragSortableList from 'react-drag-sortable'

export default class Foo extends Component {
  render() {
    return (
      <div>
        <DragSortableList
          items={[{content: (<div>A</div)}, {content:  (<div>B</div)}]}
          onSort={() => (null)}
          type="horizontal"/>
      </div>
    )
  }
}
```

**Comment by tom-s** [comment]
Both your remarks are right, I've corrected the code and doc accordingly and published the npm package. Let me know if it solve your problem !

**Comment by tom-s** [comment]
It's been 20 days, I close the issue
