### ISSUE TITLE
Getting error, cannot set prop 'rank' on undefined. 

### ISSUE THREAD

**Issue by katzman** [tom-s/react-drag-sortable#20]
Apparently it's for 'dragged' or 'placeholder' objects thats undefined, it's at line 401. I put a check in there if either is undefined then just return null. This is kind of an edge case, you really have to make an effort to break it. Seems if you drag them around quickly it can get confused. Apparently my client can do it at will and has been sending me videos of it dying on him. i included the video he sent me here, it's towards the end, like the last minute or two. I only got it to break a few times. 

Could be something in my setup, this thing is still a work in progress, it's barely a beta. 
https://drive.google.com/open?id=1_OTRpvQwWDoe-Jexu2s-zg8FkDE4ZXVP

Love some feedback, thank you!

**Comment by tom-s** [comment]
Hi. Thanks for raising an issue, but I do not have time to maintain this library anymore. Sorry, PR are welcome though !

**Comment by katzman** [comment]
I get it, no worries, thanks for the response. Do you have suggestions for a different library? 

Thanks!

**Comment by larsblumberg** [comment]
http://react-dnd.github.io/react-dnd is very good

**Comment by tom-s** [comment]
:+1: for react-dnd, I'd also add https://github.com/atlassian/react-beautiful-dnd or https://github.com/Shopify/draggable
