### ISSUE TITLE
On drag, first pixel hides the dragging item, causing flicker

### ISSUE THREAD

**Issue by dbeckhammer** [tom-s/react-drag-sortable#21]
First, thank you for this helpful component! It does exactly what I need it to do, given the project I'm working on. The only issue in my build is a single pixel that is causing a flicker. This happens when you first start dragging the item, and only lasts for a single pixel. It seems that once the item is dragged, it applies the "dragged" class, however it also applies an inline style of `position:static; display:none; transform:none` for the first pixel. Any drag beyond the first pixel the correct styles are applied: `position:absolute; display:block; transform:translate(Xpx Ypx); z-index:10; left:Xpx; top:Ypx;` - this results in a flicker that I can't get rid of with CSS alone (because the left and top aren't set).

**Comment by tom-s** [comment]
Hi. Thanks for raising an issue, but I do not have time to maintain this library anymore. Sorry, PR are welcome though !
