### ISSUE TITLE
update state onSort

### ISSUE THREAD

**Issue by alexgvozden** [tom-s/react-drag-sortable#23]
Hi,

how do you see updating the state with new order with onSort

as far as I can see you can only get elements order, and not info on new order or swap for example?
I see there is an ID attribute,  but since you increment id every time, seems there would need to be calculations

thanks for the answer, I will probably hack it out but would be interesting to hear idea of the component itself since new order is needed as end result

Thanks
Alex

**Comment by Anatejms** [comment]
AFAIR onSort is only to perform additional work after sorting. State will be updated when you drop item

**Comment by alexgvozden** [comment]
internal state of component will, but I am talking about my state, with order of items
 
state can be updated only on calling updating state plus, why would component do that when I should control what gets updated

here is small onSort function that does this....

```
  onSort(sortedList, dropEvent) {
    console.log(sortedList);
    const reducer = (accumulator, currentValue) =>
      Math.min(accumulator, parseInt(currentValue.id));
    
    // get minimum id, so we can transform 3, 2, 6, 4, 5 to 1, 0, 4, 2, 3 
    const minId = sortedList.reduce(reducer, 3000000000);
    console.log('minId', minId);

    // get id's for new order, normalized from zero - transform 3, 2, 6, 4, 5 to 1, 0, 4, 2, 3 
    const newOrder = sortedList.map(el => parseInt(el.id) - minId);
    console.log('newOrder', newOrder);

    const fields = this.state.fields.slice(0);
    let newOrderedFields = [];
    // insert new order based on new positions from newOrder
    newOrder.forEach(id => newOrderedFields.push(fields[id]));

    this.setState({ fields: newOrderedFields });
  }
```

**Comment by Anatejms** [comment]
I'm doing something like this:
```
handleSort = sortedList => {
    const { collectionItems, onCollectionUpdate } = this.props;
    const findRankByIdInSortedList = props => {
      return sortedList.find(item => item.props === props).rank;
    };

    collectionItems.sort((a, b) => {
      return findRankByIdInSortedList(a) - findRankByIdInSortedList(b);
    });

    onCollectionUpdate(collectionItems);
  };
```
