### ISSUE TITLE
Item hangs "in air" when leaving the browser window area

### ISSUE THREAD

**Issue by dmigo** [tom-s/react-drag-sortable#24]
<img width="1090" alt="screen shot 2018-05-18 at 16 27 53" src="https://user-images.githubusercontent.com/7461607/40240312-95fb4fa4-5ab8-11e8-888b-893607ad5e15.png">

Sometimes an item hangs "in air" when cursor leaves the browser window area.

Browser:
> Google Chrome
> Version 66.0.3359.181 (Official Build) (64-bit)`

OS:
> macOS Sierra
> Version 10.12.6 (16G1314)

**Comment by tom-s** [comment]
Hi. Thanks for raising an issue, but I do not have time to maintain this library anymore.
