### ISSUE TITLE
Drag using a Drag-Handle

### ISSUE THREAD

**Issue by dexter-skr** [tom-s/react-drag-sortable#27]
Hi,
First of all thanks a lot for this library. It was the easiest to integrate & achieved exactly what I wanted to.

Though I know you are not maintaining this project, the reason am raising this is to know if the feature is already available or not. ( If not I could try doing it )

Feature :
Does this library have an option to use a drag-handle (within draggable-item)  to drag.

P.S :  (No.  react-dnd seems bit complicated to integrate, due to the complexities of my project.)

**Comment by tom-s** [comment]
Hi,

There is no drag handle feature but i guess you could achieve it using the "no-drag" class. Check out the example "no-drag" where the text is draggeable but not the inputs.
