### ISSUE TITLE
Warning: Encountered two children with the same key, `item-2`.

### ISSUE THREAD

**Issue by VSV6** [tom-s/react-drag-sortable#35]
![image](https://user-images.githubusercontent.com/39857548/192238281-e0ed1737-df59-4be1-a1bd-7af623093023.png)

I'm receiving the above warning, also from the library, when I tried to arrange my columns, I'm receiving duplicate columns as below picture.

![image](https://user-images.githubusercontent.com/39857548/192238630-d5b5e666-82aa-4423-8ba6-c37bdd91a428.png)

How to solve this, I'm trying for almost 2 hrs not been able to find the solution, please do support me to solve the above problem.

I'll share my code below,

`import { useEffect, useState } from "react";
import DragSortableList from "react-drag-sortable";

import Button from "../../../components/fields/button/button.component";
import Modal from "../../../components/modal/modal.component";

import CheckedImg from "../../../assets/images/checked.svg";

const AddTableColumn = (props) => {
  const [state, setState] = useState({
    checkboxes: [],
    columns: props.selectedColumns.map((col, ind) => {
      col.key = ind;
      return col;
    }),
    // columns: [],
  });

  useEffect(() => {
    const checkboxes = props.data.map((column) => {
      let checked = false;

      if (state.columns.length) {
        checked = state.columns.some((stateCol) => {
          return stateCol.label === column.label;
        });
      }

      return {
        ...column,
        checked,
      };
    });

    const columns = [];

    state.columns.forEach((stateCol, stateIndex) => {
      props.data.forEach((column, colIndex) => {
        if (stateCol.label === column.label) {
          columns.push({
            ...stateCol,
            content: (
              <div className="tb-md-col">
                <span>{stateCol.label}</span>
              </div>
            ),
          });
        }
      });
    });

    console.log(columns);

    setState({ ...state, columns, checkboxes });
  }, []);

  const onCheckBox = (checkbox, index) => {
    const checkboxes = [...state.checkboxes];
    const currentCheckbox = checkboxes[index];
    let columns = [...state.columns];

    checkboxes[index].checked = !checkbox.checked;

    if (currentCheckbox.checked) {
      columns.push({
        // audioConfig,
        content: (
          <div className="tb-md-col">
            <span>{checkbox.label}</span>
          </div>
        ),
        label: checkbox.label,
        value: checkbox.name,
      });
    } else {
      columns = state.columns.filter(
        (column) => column.label !== checkbox.label
      );
    }
    setState({ columns, checkboxes });
  };

  const renderCheckboxes = () => {
    return state.checkboxes.map((checkbox, index) => (
      <section className="my-2 me-3 d-flex align-items-center" key={index}>
        {checkbox.checked ? (
          <img
            alt="Checked"
            onClick={() => onCheckBox(checkbox, index)}
            role="button"
            src={CheckedImg}
          />
        ) : (
          <div
            className="table-modal-checkbox"
            onClick={() => onCheckBox(checkbox, index)}
          />
        )}
        <span className="table-modal-checkbox-title">{checkbox.label}</span>
      </section>
    ));
  };

  const onClear = () => {
    const checkboxes = state.checkboxes.map((checkbox) => {
      checkbox.checked = false;
      return checkbox;
    });

    setState({ checkboxes, columns: [] });
  };

  return (
    <Modal size="xl">
      <div className="table-pg-modal-cont">
        <i
          className="fa fa-times float-end"
          onClick={() => props.toggleModal("addTableColumn", false)}
          role="button"
        />
        <p className="table-pg-modal-title">Custom Table</p>
        <p className="table-pg-modal-sec-title">
          Choose columns to show in table
        </p>
        <section className="d-flex flex-wrap">{renderCheckboxes()}</section>
        <section className="my-5">
          <p className="tb-md-sec-title">Customise the columns</p>
          <DragSortableList
            dropBackTransitionDuration={0.3}
            items={state.columns}
            moveTransitionDuration={0.3}
            onSort={(columns) => {
              setState({ ...state, columns });
            }}
            type="horizontal"
          />
        </section>
        <section className="text-center">
          <Button className="tb-sider-clr-btn" onClick={onClear}>
            CLEAR
          </Button>
          <Button
            className="tb-sider-apply-btn"
            // disabled={!checkBoxes.some((c) => c.checked)}
            onClick={() => {
              props.onApply(state.columns);
            }}
          >
            APPLY
          </Button>
        </section>
      </div>
    </Modal>
  );
};

export default AddTableColumn;
`

**Comment by tom-s** [comment]
https://github.com/tom-s/react-drag-sortable
->  `. Issues won't be solved and PRs won't be merged.`

I'm sorry but this is a very rude way of asking for help. The least you could do is provide a codesandbox link or other rather than copy pasting all your code. Also you should try to isolate the issue rather than sending all the code above.
Next time you raise on issue for some open source library, please bear in mind that maintainers usuually provide assistance on their own time, so the least you could do it make the task easier for them and be polite.
