### ISSUE TITLE
Connected lists

### ISSUE THREAD

**Issue by oyeanuj** [tom-s/react-drag-sortable#4]
Hi @tom-s! I am curious if the library also supports connected lists (i.e, dragging from one list and dropping into another)?

Thank you for open-sourcing this library!

**Comment by tom-s** [comment]
Hi. I'm afraid this (somehow a bit dated) library does not support connected list.
I believe this more recent library could help you for that kind of purpose : https://github.com/bevacqua/react-dragula

Thanks for your PR by the way

**Comment by oyeanuj** [comment]
@tom-s I just noticed that this library suddenly woke up! 😃  Since you last referred to it as dated, I am wondering if you are planning to revive this again?
