### ISSUE TITLE
Undefined errors due to invalid references exist to _

### ISSUE THREAD

**Issue by andrewjaykeen** [tom-s/react-drag-sortable#5]
It looks like you're referencing lodash directly via _.bind, _.map and _.union.  I was getting undefined errors on the console, changed 5-6 spots to reference _lodash.<func> instead, and it worked.

**Comment by tom-s** [comment]
Thanks for letting me know, please feel free to submit a PR with the changes !

**Comment by tom-s** [comment]
It's been fixed in version 1.0.1
